apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-example  # Gleicher Namespace wie das Deployment
spec:
  selector:
    app: nginx  # Selektiert die Pods mit dem Label "app: nginx"
  ports:
    - protocol: TCP
      port: 80        # Der Port, über den der Service angesprochen wird
      targetPort: 80  # Der Port im Container
  type: LoadBalancer  # Dies macht den Service öffentlich zugänglich (oder NodePort für internen Zugriff)
